apiVersion: v1
kind: ConfigMap
metadata:
  name: hummerrisk-config
data:
  hummerrisk.properties: |
    spring.datasource.url=jdbc:mysql://hr-mysql:3306/hummerrisk?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    spring.datasource.username=root
    ## 数据库密码会经过 base64 加密
    spring.datasource.password=Hummer@2022
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-hr-logs
  annotations:
    # 与nfs-storageClass.yaml metadata.name保持一致
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-hr-image
  annotations:
    # 与nfs-storageClass.yaml metadata.name保持一致
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-hr-file
  annotations:
    #与nfs-storageClass.yaml metadata.name保持一致
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    owner: hummercloud
  labels:
    app: hummerrisk
  name: hummerrisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hummerrisk
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hummerrisk
    spec:
      #tolerations:
        #- effect: NoSchedule
        #  key: node-role.kubernetes.io/master
      containers:
      - name: hummer-risk
        image: "registry.cn-beijing.aliyuncs.com/hummerrisk/hummerrisk:dev
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 500Mi
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -ec
              - curl -fsL http://localhost:8088 > /dev/null
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -ec
              - curl -fsL http://localhost:8088 > /dev/null
        volumeMounts:
          - name: config-volume
            mountPath: /opt/hummerrisk/conf
          - name: log-volume
            mountPath: /opt/hummerrisk/log
          - name: file-volume
            mountPath: /opt/hummerrisk/file
          - name: image-volume
            mountPath: /opt/hummerrisk/image
          - name: docker-sock
            mountPath: /var/run/docker.sock
        ports:
          - containerPort: 8088
      volumes:
        - name: config-volume
          configMap:
            name: hummerrisk-config
            optional: true
        - name: log-volume
          persistentVolumeClaim:
            claimName: data-hr-logs
        - name: file-volume
          persistentVolumeClaim:
            claimName: data-hr-file
        - name: image-volume
          persistentVolumeClaim:
            claimName: data-hr-image
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock