{{- $password := include "db.password" . -}}
{{ if .Values.mysql.enabled }}
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hummerrisk-mysql-password
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: mysql
type: Opaque
data:
  mysql-root-password: {{ $password | b64enc }}
{{end}}