{{- $fullName := include "hummerrisk.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hummerrisk-web-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: hummerrisk-ui
data:
  hummerrisk.conf: |-
    server {
    listen 80;
    client_max_body_size 5000m;
    server_tokens off;
    location / {
    try_files $uri / /index.html;
    alias /opt/hmr-ui/;
    }

    location = /login {
    try_files $uri /login.html;
    alias /opt/hmr-ui/;
    }

    location /prod-api/{
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://{{ $fullName }}-gateway:8080/;
    }
    }
