apiVersion: v1
kind: ConfigMap
metadata:
  name: hummerrisk-config
  namespace: {{ .Release.Namespace | quote }}
data:
  hummerrisk.properties: |
    spring.datasource.url=jdbc:mysql://{{ include "db.host" . }}:{{ include "db.port" . }}/{{ include "db.database" . }}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    spring.datasource.username={{ include "db.username" . }}
    spring.datasource.password={{ include "db.password" . }}