{{- $pvcFullName := printf "%s-%s" (include "hummerrisk.name" $) "data" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvcFullName }}-logs
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass }}
spec:
  storageClassName: "{{ .Values.global.storageClass }}"
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.logSize |quote }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvcFullName }}-image
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass }}
spec:
  storageClassName: "nfs"
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.imageSize |quote }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvcFullName }}-file
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass }}
spec:
  storageClassName: "{{ .Values.global.storageClass }}"
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.fileSize |quote }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvcFullName }}-trivy-db
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass }}
spec:
  storageClassName: "{{ .Values.global.storageClass }}"
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.trivySize |quote }}