apiVersion: v1
kind: Service
metadata:
  labels:
    app: hummerrisk-trivy-server
  name: trivy-server
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: "hummerrisk-trivy-server"
      port:  {{ .Values.trivyServer.servicePort }}
      targetPort: 4975
  selector:
    app: hummerrisk-trivy-server
  type: {{ .Values.trivyServer.serviceType }}
  sessionAffinity: {{ .Values.hummerrisk.sessionAffinity }}