apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hummerrisk-nacos
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: nacos
spec:
  serviceName: hummerrisk-nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nacos
          image: "{{ .Values.global.imageRegistry }}/hummerrisk/nacos-server:v2.2.0"
          imagePullPolicy: "IfNotPresent"
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
            - containerPort: 7848
              name: old-raft-rpc
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "hummerrisk-nacos-0.hummerrisk-nacos-headless.{{ .Release.Namespace }}.svc.cluster.local:8848 hummerrisk-nacos-1.hummerrisk-nacos-headless.{{ .Release.Namespace }}.svc.cluster.local:8848 hummerrisk-nacos-2.hummerrisk-nacos-headless.{{ .Release.Namespace }}.svc.cluster.local:8848"
  selector:
    matchLabels:
      app: nacos