{{ if .Values.mysql.enabled }}
{{- $pvcFullName := printf "%s-%s" (include "hummerrisk.name" $) "data" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvcFullName }}-mysql
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.global.storageClass | quote }}
spec:
  storageClassName: {{ .Values.global.storageClass |quote }}
  accessModes:
    {{- range .Values.storage.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.dbSize | quote }}
{{end}}