{{- $pvcFullName := printf "%s-%s" (include "hummerrisk.name" $) "data" }}
{{- $fullName := include "hummerrisk.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    owner: hummercloud-{{ .Release.Namespace }}
  labels:
    app: hummerrisk-cloud
  name: hummerrisk-cloud
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.hummerrisk.replicas }}
  selector:
    matchLabels:
      app: hummerrisk-cloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hummerrisk-cloud
    spec:
      #tolerations:
        #- effect: NoSchedule
        #  key: node-role.kubernetes.io/master
      containers:
      - name: hummerrisk
        image: "{{ .Values.global.imageRegistry }}/hummerrisk/hmr-cloud:{{ .Values.hummerrisk.image.tag }}"
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: {{ .Values.hummerrisk.image.pullPolicy }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: hummerrisk-config
        env:
          - name: JAVA_OPTIONS
            value: "-Dfile.encoding=utf-8 -Djava.awt.headless=true -DHMR_NACOS_SERVER_ADDR={{ include "nacos.host" . }}"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -ec
              - curl -fsL http://localhost:9400/healthz > /dev/null
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -ec
              - curl -fsL http://localhost:9400/healthz > /dev/null
        volumeMounts:
          - name: log-volume
            mountPath: /opt/hummerrisk/log
        ports:
          - containerPort: 9400
          - containerPort: 9401
          - containerPort: 8002
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: {{ $pvcFullName }}-logs