{{- $pvcFullName := printf "%s-%s" (include "hummerrisk.name" $) "data" }}
{{- $fullName := include "hummerrisk.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    owner: hummercloud-{{ .Release.Namespace }}
  labels:
    app: hummerrisk
  name: hummerrisk-flyway
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.hummerrisk.replicas }}
  selector:
    matchLabels:
      app: hummerrisk-flyway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hummerrisk-flyway
    spec:
      #tolerations:
        #- effect: NoSchedule
        #  key: node-role.kubernetes.io/master
      containers:
      - name: hummerrisk-flyway
        image: "{{ .Values.global.imageRegistry }}/hummerrisk/hmr-flyway:{{ .Values.hummerrisk.image.tag }}"
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: hummerrisk-config
        env:
          - name: JAVA_OPTIONS
            value: "-Dfile.encoding=utf-8 -Djava.awt.headless=true -DHMR_MYSQL_HOST={{ include "db.host" . }} -DHMR_MYSQL_PORT={{ include "db.port" . }} -DHMR_MYSQL_DB_NACOS={{ include "nacos.db" . }} -DHMR_MYSQL_USER={{ include "db.username" . }} -DHMR_MYSQL_PASSWORD={{ include "db.password" . }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 1
        startupProbe:
          httpGet:
            path: /healthz
            port: 9000
          failureThreshold: 10
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
          - containerPort: 9000