{{- $pvcFullName := printf "%s-%s" (include "hummerrisk.name" $) "data" }}
{{- $fullName := include "hummerrisk.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    owner: hummercloud-{{ .Release.Namespace }}
  labels:
    app: hummerrisk-k8s
  name: hummerrisk-k8s
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.hummerrisk.replicas }}
  selector:
    matchLabels:
      app: hummerrisk-k8s
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hummerrisk-k8s
    spec:
      initContainers:
        - name: db-init
          image: "{{ .Values.global.imageRegistry }}/hummerrisk/trivy-db:{{ .Values.hummerrisk.image.tag }}-{{ .Values.trivy.trivyDBVersion }}"
          imagePullPolicy: {{ .Values.hummerrisk.image.pullPolicy }}
          command: [ 'sh','-c' ]
          args: [ 'tar zxf /db/trivy-offline-v2-{{ .Values.trivy.trivyDBVersion }}.db.tar.gz -C /opt' ]
          volumeMounts:
            - mountPath: /opt
              name: trivy-db
      #tolerations:
        #- effect: NoSchedule
        #  key: node-role.kubernetes.io/master
      containers:
      - name: hummerrisk-k8s
        image: "{{ .Values.global.imageRegistry }}/hummerrisk/hmr-k8s:{{ .Values.hummerrisk.image.tag }}"
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: hummerrisk-config
        env:
          - name: JAVA_OPTIONS
            value: "-Dfile.encoding=utf-8 -Djava.awt.headless=true -DHMR_NACOS_SERVER_ADDR={{ include "nacos.host" . }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9500
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9500
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 1
        startupProbe:
          httpGet:
            path: /healthz
            port: 9500
          failureThreshold: 10
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
          - containerPort: 9500
          - containerPort: 9501
          - containerPort: 8003
        volumeMounts:
          - mountPath: /opt/hummerrisk/trivy
            name: data-k8s
            subPath: trivy
          - mountPath: /opt/hummerrisk/file
            name: data-k8s
            subPath: file
          - mountPath: /opt/hummerrisk/image
            name: data-k8s
            subPath: image
          - name: trivy-db
            mountPath: /root/.cache/trivy/
      volumes:
        - name: data-k8s
          persistentVolumeClaim:
            claimName: {{ $pvcFullName }}-k8s
        - name: trivy-db
          persistentVolumeClaim:
            claimName: {{ $pvcFullName }}-trivy-db