apiVersion: v1
kind: Service
metadata:
  labels:
    app: hummerrisk
  name: hummerrisk-web
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: "web-hummerrisk"
      port:  {{ .Values.hummerrisk.servicePort }}
      targetPort: 8088
  selector:
    app: hummerrisk
  type: ClusterIP
  sessionAffinity: {{ .Values.hummerrisk.sessionAffinity }}