apiVersion: v1
kind: Service
metadata:
  labels:
    app: hummerrisk
  name: hummerrisk-web
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: "hummerrisk-web"
      port:  {{ .Values.hummerrisk.servicePort }}
      targetPort: 8088
  selector:
    app: hummerrisk
  type: {{ .Values.hummerrisk.serviceType }}
  sessionAffinity: {{ .Values.hummerrisk.sessionAffinity }}