{{- if and .Values.serviceAccount.create }}
# Source: mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hummerrisk
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
secrets:
  - name: hummerrisk-mysql
{{- end }}