apiVersion: v1
kind: ConfigMap
metadata:
  name: hummerrisk-config
data:
  hummerrisk.properties: |
    spring.datasource.url=jdbc:mysql://hr-mysql:3306/hummerrisk?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    spring.datasource.username=root
    ## 数据库密码会经过 base64 加密
    spring.datasource.password=Hummer@2022
