{{- $password := include "redis.password" . -}}
{{ if .Values.redis.enabled }}
# Source: redis/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hummerrisk-redis-password
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: redis
type: Opaque
data:
  redis-password: {{ $password | b64enc }}
{{end}}